export const titleRole = {
	project: "Quản lý dự án",
	role: "Quản lý quyền hạn",
	user: "Quản lý người dùng",
	department: "Quản lý phòng ban",
	brand: "Quản lý thương hiệu",
	kpibonus: "Quản lý kpi bonus",
	team: "Quản lý nhóm",
	seo: "Quản lý bài viết seo",
	domain: "Quản lý domain",
	personal: "Quản lý cá nhân",
	log: "Quản lý log",
	status: "Quản lý trạng thái",
	label: "Quản lý label",
	task: "Quản lý nhiệm vụ",
	checklist: "Quản lý công việc",
	comment: "Quản lý bình luận",
	"day-off": "Quản lý ngày nghỉ",
	"user-reported-chart": "Biểu đồ các công việc đã báo cáo theo nhân viên",
	"users-reported-chart": "Biểu đồ các nhân viên đã báo cáo công việc",
	"tasks-reported-chart": "Biểu đồ các công việc đã báo cáo",
};

export let defaultRole = {
	project: {create: false, read: false, update: false, delete: false},
	role: {create: false, read: false, update: false, delete: false},
	user: {create: false, read: false, update: false, delete: false},
	department: {create: false, read: false, update: false, delete: false},
	brand: {create: false, read: false, update: false, delete: false},
	kpibonus: {create: false, read: false, update: false, delete: false},
	team: {create: false, read: false, update: false, delete: false},
	seo: {create: false, read: false, update: false, delete: false},
	domain: {create: false, read: false, update: false, delete: false},
	personal: {create: false, read: false, update: false, delete: false},
	log: {create: false, read: false, update: false, delete: false},
	status: {create: false, read: false, update: false, delete: false},
	label: {create: false, read: false, update: false, delete: false},
	task: {create: false, read: false, update: false, delete: false},
	checklist: {create: false, read: false, update: false, delete: false},
	comment: {create: false, read: false, update: false, delete: false},
	"day-off": {create: false, read: false, update: false, delete: false},
	"user-reported-chart": {
		create: false,
		read: false,
		update: false,
		delete: false,
	},
	"users-reported-chart": {
		create: false,
		read: false,
		update: false,
		delete: false,
	},
	"tasks-reported-chart": {
		create: false,
		read: false,
		update: false,
		delete: false,
	},
};
